package TestPages;


//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LogINTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();

 driver.get("http://10.11.200.14:9040/eocas/logIn.do");
 driver.manage().window().setSize(new Dimension(1382, 744));
 driver.findElement(By.id("username")).click();
 driver.findElement(By.id("username")).sendKeys("k.rm");//login username(XL_1), Please make an XL input chatgpt
 driver.findElement(By.id("password")).sendKeys("123456");//login Pass(XL_2),Please make an XL input chatgpt
 driver.findElement(By.linkText("Sign In")).click();
 try {
   Thread.sleep(3000);
 } catch (InterruptedException e) {
   e.printStackTrace();
 }
 driver.findElement(By.linkText("Sign In")).click();
 try {
   Thread.sleep(3000);
 } catch (InterruptedException e) {
   e.printStackTrace();
 }
 driver.findElement(By.id("CFC")).click();
}
    @After
    public void tearDown() {
        driver.quit();
    }
@Test
public void NewApplicationGenerationSimplified() throws InterruptedException {
  driver.get("http://10.11.200.14:9040/eocas/loadDashboardDataGridList.do");
  Thread.sleep(2000);
  driver.findElement(By.xpath("//a[normalize-space()='New Application']")).click();
  try {
    Thread.sleep(5000);
  } catch (InterruptedException e) {
    e.printStackTrace();
  }
  driver.findElement(By.xpath("//button[contains(text(),\'De-Dup Check\')]")).click();
  try {
    Thread.sleep(5000);
  } catch (InterruptedException e) {
    e.printStackTrace();
  }
  driver.findElement(By.name("checkedFlagCode")).click();
  {
    WebElement dropdown = driver.findElement(By.name("checkedFlagCode"));
    dropdown.findElement(By.xpath("//option[. = 'YES']")).click();
  }
  driver.findElement(By.id("exeShowHideBtn")).click();
  driver.findElement(By.xpath("//button[contains(text(),\'Back\')]")).click();
  driver.findElement(By.name("customerName")).click();
  //random Name Generate Start
  //vars.put("randomApplicantFullName", js.executeScript("var firstNames = [   \"Abdul\",   \"Rafiqul\",   \"Hasan\",   \"Nazmul\",   \"Sohail\",   \"Farhana\",   \"Shamima\",   \"Mitu\",   \"Sadia\",   \"Jannatul\" ]; var lastNames = [   \"Rahman\",   \"Chowdhury\",   \"Khan\",   \"Ahmed\",   \"Hossain\",   \"Molla\",   \"Miah\",   \"Sarker\",   \"Ferdous\",   \"Kabir\" ];  var randomFirstName = firstNames[Math.floor(Math.random() * firstNames.length)]; var randomLastName = lastNames[Math.floor(Math.random() * lastNames.length)];  var fullName = randomFirstName + \" \" + randomLastName; return fullName;"));
  //random Name Generate End
  driver.findElement(By.name("customerName")).sendKeys("Abdul"); // random Generate Name Input, Name Input(full name_xl3)
 // vars.put("vars.get("randomApplicantFullName").toString()", driver.findElement(By.name("customerName")).getAttribute("value"));
//  vars.put("randomApplicantFullName", driver.findElement(By.name("customerName")).getAttribute("value"));
 // vars.put("randomApplicantFullName", driver.findElement(By.name("customerName")).getAttribute("value"));

  driver.findElement(By.name("basicAliasName")).sendKeys("Robin"); // Nick Name input, nick name(XL4),Please make an XL input chatgpt
  driver.findElement(By.name("basicCustType")).click();
  {
    WebElement dropdown = driver.findElement(By.name("basicCustType")); // dropdown
    dropdown.findElement(By.xpath("//option[. = 'SALARIED']")).click();//Xl input instead of BUSINESSMAN, SALARIED,LAND LORD, PROFESSIONAL.Please make an XL input chatgpt. create a dropdown field(Dropdown list:BUSINESSMAN, SALARIED,LAND LORD, PROFESSIONAL)
  }
  driver.findElement(By.name("basicCustCategory")).click();
  {
    WebElement dropdown = driver.findElement(By.name("basicCustCategory"));
    dropdown.findElement(By.xpath("//option[. = 'Priority']")).click();//XL DROPDOWN input instead of Employed, Priority, Regular, Self-Employed Professionals, Salaried Individuals. Please make an XL input chatgpt. create a dropdown field(Dropdown list:Employed, Priority, Regular, Self-Employed Professionals, Salaried Individuals.)
  }
  driver.findElement(By.name("basicCustCategoryNew")).click();
  {
    WebElement dropdown = driver.findElement(By.name("basicCustCategoryNew"));
    dropdown.findElement(By.xpath("//option[. = 'Priority']")).click();//Xl Dropdown input instead of Payroll, Priority, Regular, Payroll & Priority, Corporate Individual  & Multiple. Please make an XL input chatgpt. create a dropdown field(Dropdown list:Payroll, Priority, Regular, Payroll & Priority, Corporate Individual  & Multiple.)
  }
  driver.findElement(By.id("branchInfoSearch")).click();
    Thread.sleep(2000);
  driver.findElement(By.xpath("//td[contains(text(),\'Banani\')]")).click();
  driver.findElement(By.id("basicAlternativeRM")).click();
  driver.findElement(By.name("assesmentTypeCode")).click();
  {
    WebElement dropdown = driver.findElement(By.name("assesmentTypeCode"));
    dropdown.findElement(By.xpath("//option[. = 'SIMPLIFIED ASSESSMENT']")).click();// XL Dropdown input instead of SIMPLIFIED ASSESSMENT, CASH BASED ASSESSMENT.Please make an XL input chatgpt. create a dropdown field(SIMPLIFIED ASSESSMENT, CASH BASED ASSESSMENT.)
  }
  driver.findElement(By.id("appIdGenerate")).click();
  try {
    Thread.sleep(10000);
  } catch (InterruptedException e) {
    e.printStackTrace();
  }
}
}
